scriptencoding utf-8
filetype plugin indent on
runtime! macros/matchit.vim
syntax on
colorscheme greyscale
let mapleader="\<Space>"
let &showbreak='› '
set autoindent
set autoread
set backspace=indent,eol,start
set backup
set backupcopy=auto
set backupdir=$HOME/.vim/backup
set belloff=all
set breakindent
set breakindentopt=shift:2
set clipboard=
set cmdheight=1
set cmdwinheight=30
set complete=.,w,b,u
set completeopt=menu
set concealcursor=nvic
set conceallevel=3
set cpoptions=BceFs
set cryptmethod=blowfish2
set cscopequickfix=s-,c-,d-,i-,t-,e-,a-,g-
set cscopetagorder=0
set diffexpr=
set diffopt=iwhite,filler,vertical
set directory=$HOME/.vim/swap//
set encoding=utf-8
set endofline
set equalalways
set expandtab
set fileencoding=utf-8
set fileencodings=utf-8
set fileformats=unix,dos,mac
set fillchars=
set foldclose=
set foldexpr=fold#method(v:lnum)
set foldlevel=1
set foldmethod=expr
set foldminlines=0
set foldnestmax=3
set foldopen=search,insert,quickfix,tag,undo
set formatoptions=cqrj
set guicursor=a:block-Cursor
set guifont=Source\ Code\ Pro\ Regular\ 13
set guioptions=i
set hidden
set history=1000
set hlsearch
set incsearch
set laststatus=2
set lazyredraw
set linebreak
set listchars=tab:▸\ ,eol:¬,space:·,extends:»,precedes:«,nbsp:○
set magic
set menuitems=10
set mouse=
set noautowrite
set noautowriteall
set nobomb
set noconfirm
set noerrorbells
set nofoldenable
set nogdefault
set noignorecase
set nojoinspaces
set nolist
set nomodeline
set nomore
set nopaste
set noshowcmd
set showmode
set nospell
set notimeout
set nowrap
set nowritebackup
set nrformats=
set number
set path=.,**
set previewheight=12
set pumheight=10
set report=0
set scrolloff=5
set selectmode=
set sessionoptions=blank,buffers,winsize
set shell=bash
set shiftwidth=4
set shortmess=aoOTIcsAF
set showtabline=0
set sidescrolloff=10
set smartindent
set smarttab
set softtabstop=4
set spellcapcheck=
set spelllang=en
set splitbelow
set splitright
set startofline
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc,.png,.jpg
set swapfile
set switchbuf=useopen
set synmaxcol=800
set t_Co=256
set t_ut=
set t_vb=
set tabstop=4
set tagbsearch
set tagcase=followic
set tagrelative
set tags=./tags;/
set termencoding=utf-8
set textwidth=72
set title
set ttimeout
set ttimeoutlen=5
set ttyfast
set undodir=$HOME/.vim/undo//
set undofile
set undolevels=5000
set updatecount=10
set updatetime=2000
set viewoptions=folds,options,cursor,slash,unix
set viminfo='30,<50,s10,h
set virtualedit=block
set visualbell
set warn
set wildignore=.svn,.git,tags,cscope.out
set wildignorecase
set wildmenu
set wildmode=longest:full,full
set winminheight=0
set winminwidth=0
set wrapscan
