#!/bin/bash
find $PWD -name "*.php" -print > /tmp/phpfiles
cat /tmp/phpfiles | ctags --PHP-kinds=cdf --languages=PHP --totals=no --exclude=".git" --exclude=".svn" --tag-relative --recurse --fields=+ia --append
rm -f /tmp/phpfiles
exit 0
